name: bmi_do
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  flutter_switch: ^0.3.2
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/InterRegular.ttf
          weight: 400
        - asset: fonts/InterMedium.ttf
          weight: 500
        - asset: fonts/InterBold.ttf
          weight: 700
        - asset: fonts/InterExtraBoldItalic.ttf
          weight: 800
          style: italic
